name: Update Port with PR Information

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  update-port:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Port with PR Information
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          identifier: githubPullRequest
          title: Pull Request
          blueprint: githubPullRequest
          properties: |-
            {
              "creator": "string",
              "assignees": [],
              "reviewers": [],
              "status": "merged",
              "closedAt": "2024-05-30T06:14:31.251Z",
              "updatedAt": "2024-05-30T06:14:31.251Z",
              "mergedAt": "2024-05-30T06:14:31.251Z",
              "link": "https://example.com",
              "author": "string",
              "repository": "string"
            }


      
